cask_args appdir: "/Applications"
tap "caskroom/cask"
tap "caskroom/versions"
tap "chef/chef"

# Core dependencies
cask "java" unless system "/usr/libexec/java_home --failfast"
cask "xquartz"

# Command line apps to install via Homebrew
brew "ack"
brew "ansible"
brew "asciinema"
brew "awk"
brew "aws-shell"
brew "awscli"
brew "bash-completion"
brew "bash"
brew "bc"
brew "bfg"
brew "boost"
brew "bzip2"
brew "cloc"
brew "curl"
brew "diffstat"
brew "diffutils"
brew "ec2-ami-tools"
brew "ec2-api-tools"
brew "ed"
brew "elm"
brew "emacs", args: ["with-cocoa", "with-gnutls"]
brew "expect"
brew "ffmpeg"
brew "file-formula"
brew "filebeat"
brew "findutils"
brew "gnu-tar"
brew "gnupg2"
brew "go"
brew "gpatch"
brew "gpg-agent"
brew "gradle"
brew "graphicsmagick"
brew "grep"
brew "groff"
brew "gzip"
brew "heroku"
brew "httpie"
brew "htop"
brew "imagemagick"
brew "jq"
brew "kafkacat"
brew "kops"
brew "kubernetes-cli"
brew "kubernetes-helm"
brew "leiningen"
brew "less"
brew "libxml2"
brew "libxslt"
brew "lsof"
brew "lua"
brew "luajit"
brew "mad"
brew "make"
brew "mas"
brew "maven"
brew "md5sha1sum"
brew "minimesos"
brew "nano"
brew "ncurses"
brew "node"
brew "openssl"
brew "p7zip"
brew "packer"
brew "phantomjs"
brew "pipenv"
brew "pv"
brew "python3"
brew "rsync"
brew "sbt"
brew "screen"
brew "shellcheck"
brew "socat"
brew "sox"
brew "sqlite"
brew "ssh-copy-id"
brew "tcpdump"
brew "terraform"
brew "terragrunt"
brew "thrift"
brew "tmux"
brew "tree"
brew "unrar"
brew "unzip"
brew "vim", args: ["with-client-server", "with-luajit"]
brew "wget", args: ["with-gpgme"]
brew "whois"
brew "yarn"
brew "zlib"
brew "zsh"

# Desktop apps to install via Cask
cask "ableton-live-standard"
cask "adobe-creative-cloud"
cask "atom"
cask "betterzip"
cask "bettertouchtool"
cask "caffeine"
cask "charles"
cask "chefdk"
cask "consul-cli"
cask "dash"
cask "datagrip"
cask "deckset"
cask "docker-edge"
cask "eclipse-java"
cask "firefox"
cask "google-chrome-canary"
cask "google-chrome"
cask "google-cloud-sdk"
cask "handbrake"
cask "insomnia"
cask "intellij-idea"
cask "istat-menus"
cask "iterm2"
cask "keybase"
cask "microsoft-office"
cask "minikube"
cask "osxfuse"
cask "pritunl"
cask "pycharm"
cask "quicken"
cask "screenflow"
cask "sketch"
cask "skype"
cask "slack"
cask "sourcetree"
cask "spectacle"
cask "switchresx"
cask "toggl-beta"
cask "transmit"
cask "vagrant"
cask "virtualbox"
cask "viscosity"
cask "visual-studio-code"
cask "vmware-fusion"
cask "zoomus"

# Desktop apps to install via Mac App Store
mas "1Password", id: 443987910
mas "Disk Expert", id: 488920185
mas "Fantastical 2", id: 975937182
mas "Keynote", id: 409183694
mas "Microsoft Remote Desktop", id: 715768417
mas "Mindnode 2", id: 992076693
mas "Numbers", id: 409203825
mas "Omnigraffle 7", id: 1142578753
mas "Pages", id: 409201541
mas "Power JSON Editor", id: 499768540
mas "Skitch", id: 425955336
mas "Spark", 1176895641
mas "Textual 7", id: 1262957439
mas "WhatsApp Desktop", id: 1147396723
